name: Build & Test Solution
on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Project
      run: dotnet build --configuration Release

    - name: Install Coverlet
      run: dotnet tool install --global coverlet.console
      shell: pwsh

    - name: Run unit tests with coverage
      run: |
        $testDlls = Get-ChildItem -Path . -Recurse -Include '*Tests.dll' -Filter '*.dll' | Where-Object { $_.FullName -like "*\bin\*" } | Select-Object -ExpandProperty FullName
        foreach ($dll in $testDlls) {
          Write-Output "Running tests on: $dll"
          $dllName = [System.IO.Path]::GetFileNameWithoutExtension($dll)
          coverlet $dll --target "dotnet" --targetargs "test $dll" --format "opencover" --output "./$dllName.coverage.opencover.xml" --exclude "[*.Tests]*"
        }
      shell: pwsh

    - name: Report code coverage
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: |
          **/*.coverage.opencover.xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}