name: Build & Test .NET Framework

on:
  pull_request:
    branches:
      - '*/feat/*'
  push:
    branches:
      - '*/feat/*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build app for release
      run: msbuild AetherFlow.FakeXrmEasy.Plugins.sln -t:rebuild -verbosity:diag -property:Configuration=Release
