name: Build & Test .NET Framework

on:
  pull_request:
    branches:
      - '*/feat/*'
  push:
    branches:
      - '*/feat/*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1.2

    - name: Setup NuGet.exe
      uses: nuget/setup-nuget@v2

    - name: install opencover
      run: choco install opencover.portable

    - name: Restore Nuget Packages
      run: nuget restore AetherFlow.FakeXrmEasy.Plugins.sln

    - name: Build app for release
      run: msbuild AetherFlow.FakeXrmEasy.Plugins.sln -t:rebuild -v:diag -property:Configuration=Release

    - name: Run Tests
      run: OpenCover.Console.exe -register:user -target:"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:""AetherFlow.FakeXrmEasy.Plugins.Tests\bin\Release\AetherFlow.FakeXrmEasy.Plugins.Tests.dll" -filter:"+[UnitTestTargetProject*]* -[MyUnitTests*]*" -output:".\MyProject_coverage.xml"

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}


