name: Build & Test .NET Framework

on:
  pull_request:
    branches:
      - '*/feat/*'
  push:
    branches:
      - '*/feat/*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Install NUnit Console Runner
      run: |
        choco install nunit-console --version=3.11.1
        refreshenv

    - name: Find and Run Tests
      run: |
        $testDirs = Get-ChildItem -Recurse -Directory -Filter '*.test'
        foreach ($testDir in $testDirs) {
          Write-Output "Running tests in $testDir"
          $csprojFile = Get-ChildItem "$testDir.FullName" -Filter '*.csproj' -Recurse
          if ($csprojFile) {
            Write-Output "Found project file: $csprojFile"
            & 'C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe' "$csprojFile.FullName"
          } else {
            Write-Output "No .csproj file found in $testDir"
          }
        }

    - name: Setup NuGet.exe
      uses: nuget/setup-nuget@v2

    - name: Restore Nuget Packages
      run: nuget restore AetherFlow.FakeXrmEasy.Plugins.sln

    - name: Build app for release
      run: msbuild AetherFlow.FakeXrmEasy.Plugins.sln -t:rebuild -property:Configuration=Release
