name: Build & Test .NET Framework

on:
  pull_request:
    branches:
      - '*/feat/*'
  push:
    branches:
      - '*/feat/*'

env:
  PROJECT_TO_PUBLISH: AetherFlow.FakeXrmEasy.Plugins/AetherFlow.FakeXrmEasy.Plugins.csproj

jobs:
  build:
    uses: ./.github/workflows/jobs/BuildAndTestSolution.yml

  publish:
    needs: build
    uses: ./.github/workflows/jobs/PublishNugetPackage.yml
    with:
      ProjectPath: ${{env.PROJECT_TO_PUBLISH}}