name: Build & Test .NET Framework

on:
  pull_request:
    branches:
      - '*/feat/*'
  push:
    branches:
      - '*/feat/*'

jobs:
  build:
    uses: ./.github/workflows/BuildAndTestSolution.yml

  publish:
    needs: build
    uses: ./.github/workflows/PublishNugetPackage.yml
    with:
      ProjectPath: AetherFlow.FakeXrmEasy.Plugins/AetherFlow.FakeXrmEasy.Plugins.csproj